### PR TITLE
Removed IDE specific from .gitignore

### PR DESCRIPTION
**Pull request by kandula-aswin**

### CODE REVIEW

**Comment by ricksbrown** [comment]
For discussion - I argue that in an ideal world all *user specific* gitignore entries should be in the user's own [global gitignore](https://www.atlassian.com/git/tutorials/gitignore#global-git-ignore-rules).

gitignore entries pertaining to things like specific:
 * IDE
* editor
* operating system
etc  

should not be in the gitignore but rather in the user's global gitignore.

Project specific entries, for example [Maven excludes](https://www.gitignore.io/api/maven), should be in the project gitignore.

**Comment by ghost** [comment]
I agree with @ricksbrown: IDE specific ignores should be in the user's gitignore. This PR should not be accepted. @jonathanaustin this is your project, what do you think?

**Comment by ricksbrown** [comment]
Yes, I like it. I am now convinced that this is the "one true path" for gitignore.
It looks so nice and clean this way and all the mess is hidden away in the user's own global gitignore.
👍

**Review by ricksbrown — APPROVED** [review]
LGTM

**Pull request merged**
